config/routes.rb
Rails.application.routes.draw do

  root 'about#index'
  get 'about/speakers' => 'about#speakers'
  get 'about' => 'about#about'
  get 'calendar' => 'about#calendar'
  get 'about/sponsor' => 'about#sponsor'
  get 'about/request-to-speak' => 'about#request_to_speak'

  resources :users, only: [:new, :create]
  get 'users/validate/:id' => 'users#validate', as: 'validate_user'
  get 'users/profile' => 'users#show', as: 'user_profile'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'users/edit' => 'users#edit', as: 'edit_user'
  get 'users/edit/password' => 'users#edit_password', as: 'edit_user_password'
  patch 'users/update' => 'users#update', as: 'user'
  patch 'users/update/password' => 'users#update_password', as: 'update_user_password'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  get 'logout' => 'sessions#logout'

  resources :speakers

  resources :venues

  resources :sponsors

  resources :agencies

  resources :events
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /[^@]+@fedscoop.com/
  # validates :password, presence: true
  before_validation { |user|
    user.first_name = user.first_name.strip
    user.last_name = user.last_name.strip
    user.email = user.email.strip
    user.email = user.email.downcase
  }

  def name
    return "#{self.first_name} #{self.last_name}"
  end

  alias :to_s :name

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params[:email] = user_params[:email].downcase
    @user = User.new(user_params)
    @user.validated = false
    @user.admin = false
    @user.validation_hex = SecureRandom.hex(10)
    if @user.save
      UsersMailer.welcome_email(@user).deliver
      flash[:message] = "Please check your email to validate your account"
      redirect_to root_path
    else
      flash[:message] = "Something went wrong. Please try again."
      redirect_to new_user_path
    end
  end

  def show
    user = current_user
    if logged_in? && user.validated
      @user = user
    else
      flash[:message] = "You must be logged in to view that."
      redirect_to root_path
    end
  end

  def validate
    user = User.find_by_validation_hex(params[:id])
    if !user.validated
      @user = user
      session[:user_id] = user.id
      @user.validated = true
      @user.save!
      redirect_to dashboard_path
    else
      flash[:message] = "This user has already been validated"
      redirect_to root_path
    end
  end

  def dashboard
    if_logged_in { @user = current_user }
  end

  def edit
    if_logged_in { @user = current_user }
  end

  def update
    user = current_user
    if !user_params[:email].match /[^@]+@fedscoop.com/
      flash[:message] = "Email needs to be an '@fedscoop.com' address."
      redirect_to edit_user_path
    elsif User.update user.id, user_params
      flash[:message] = "Your profile updated successfully!"
      redirect_to user_profile_path
    else
      flash[:message] = "Oops, something went wrong!"
      redirect_to edit_user_path
    end
  end

  def edit_password
    if_logged_in { @user = current_user }
  end

  def update_password
    user = current_user
    if user.authenticate params[:old_password]
      User.update user.id, user_params
      flash[:message] = "Password Updated Successfully"
      redirect_to user_profile_path
    else
      flash[:message] = "Incorrect password. Try again."
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/views/users/dashboard.html.haml
%h1= @user.first_name + "'s FedScoop Events Dashboard"
%br

.dashboard-events
  %h2 Events
  %br
  %p
    %a{ href: "#{events_path}" } All Events
  %p
    %a{ href: "#{new_event_path}" } New Event

.dashboard-speakers
  %h2 Speakers
  %br
  %p
    %a{ href: "#{speakers_path}" } All Speakers
  %p
    %a{ href: "#{new_speaker_path}" } New Speaker

.dashboard-agencies
  %h2 Agencies / Employers
  %br
  %p
    %a{ href: "#{agencies_path}" } All Agencies / Employers
  %p
    %a{ href: "#{new_agency_path}" } New Agency / Employer

.dashboard-venues
  %h2 Venues
  %br
  %p
    %a{ href: "#{venues_path}" } All Venues
  %p
    %a{ href: "#{new_venue_path}" } New Venue

.dashboard-sponsors
  %h2 Sponsors
  %br
  %p
    %a{ href: "#{sponsors_path}" } All Sponsors
  %p
    %a{ href: "#{new_sponsor_path}" } New Sponsor

.dashboard-events
  %h2 Account
  %br
  %p
    %a{ href: "#{user_profile_path}" } My Profile

app/views/users/edit.html.haml
%h1 Edit Your Profile
%br
%br
.form
  = form_for @user do |f|
    %b First Name:
    = f.text_field :first_name
    %br
    %b Last Name:
    = f.text_field :last_name
    %br
    %b Email Address:
    = f.text_field :email, style: "width:300px;"
    %br
    = f.submit "Save"
  %a{ href: "#{edit_user_password_path}" } Update Password Instead

.wait-overlay
  %img{ src: '/images/loading.gif' }

app/views/users/edit_password.html.haml
%h1 Edit Your Password
%br
%br
.form
  = form_for @user, url: update_user_password_path, method: :patch do |f|
    Current Password:
    = password_field_tag :old_password
    %br
    New Password:
    = f.password_field :password, required: true, class: 'new-user-pass'
    %br
    Confirm New Password:
    = f.password_field :password_confirmation, required: true, class: 'new-user-pass-conf'
    %br
    = f.submit "Save New Password"

app/views/users/new.html.haml
%h1 Sign up
%br
= form_for @user, url: { action: 'create' } do |f|
  %b First Name:
  = f.text_field :first_name, required: true
  %br
  %b Last Name:
  = f.text_field :last_name, required: true
  %br
  %b Email:
  = f.email_field :email, required: true, pattern: '[^@]+@fedscoop.com', class: 'new-user-email'
  %span.email-valid Email must be a "@fedscoop.com" email.
  %br
  %b Password:
  = f.password_field :password, required: true, class: 'new-user-pass'
  %br
  %b Confirm Password:
  = f.password_field :password_confirmation, required: true, class: 'new-user-pass-conf'
  %span.password-error
  %br
  = f.submit

app/views/users/show.html.haml
%h1= @user.name + "'s Profile"
%br
%br
%b Email:
= @user.email
%br
%br
%a{ href: "#{edit_user_path}" } Edit your account information