config/routes.rb
Rails.application.routes.draw do

  root 'about#index'
  get 'about/speakers' => 'about#speakers'
  get 'about' => 'about#about'
  get 'calendar' => 'about#calendar'
  get 'about/sponsor' => 'about#sponsor'
  get 'about/request-to-speak' => 'about#request_to_speak'

  resources :users, only: [:new, :create]
  get 'users/validate/:id' => 'users#validate', as: 'validate_user'
  get 'users/profile' => 'users#show', as: 'user_profile'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'users/edit' => 'users#edit', as: 'edit_user'
  get 'users/edit/password' => 'users#edit_password', as: 'edit_user_password'
  patch 'users/update' => 'users#update', as: 'user'
  patch 'users/update/password' => 'users#update_password', as: 'update_user_password'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  get 'logout' => 'sessions#logout'

  resources :speakers

  resources :venues

  resources :sponsors

  resources :agencies

  resources :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :speaking_engagements
  has_many :sponsorships
  has_many :speakers, through: :speaking_engagements
  has_many :sponsors, through: :sponsorships
  belongs_to :venue
  before_save { |event|
    speaker_objects_to_ids
    event.agenda = event.agenda.to_yaml if event.agenda
  }

  def self.past_events
    Event.where('date < ?', DateTime.now).order("date DESC").inject(Hash.new) { |hash, event|
      if hash[event.date.year.to_s]
        hash[event.date.year.to_s] << event
        hash[event.date.year.to_s].sort_by! { |event| event.date }.reverse!
        hash
      else
        hash[event.date.year.to_s] = [event]
        hash
      end
    }
  end

  def self.events_by_year(all = true)
    e = nil
    all ? e = Event.all : e = Event.where(live: true)
    e.order("date DESC").inject(Hash.new) { |hash, event|
      if hash[event.date.year.to_s]
        hash[event.date.year.to_s] << event
        hash[event.date.year.to_s].sort_by! { |event| event.date }.reverse!
        hash
      else
        hash[event.date.year.to_s] = [event]
        hash
      end
    }
  end

  def agenda
    return_value = super
    if return_value.class == String
      agenda = YAML.load(return_value) if return_value
      return speaker_ids_to_objects agenda
    else
      return return_value
    end
  end

  def to_s
    self.name
  end

  private

  def speaker_objects_to_ids
    if self.agenda.class == Array
      self.agenda.each do |i|
        i[:speaker] = lambda{
          if i[:speaker]
            return i[:speaker].id
          else
            return nil
          end
        }.call
      end
    end
  end

  def speaker_ids_to_objects(agenda)
    agenda.each do |i|
      id = lambda {
        if i[:speaker].class == Speaker
          return i[:speaker].id
        else
          return i[:speaker].to_i
        end
      }.call
      i[:speaker] = Speaker.find_by_id(id)
    end
    agenda
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    if_logged_in { @events_by_year = Event.events_by_year }
  end

  def show
    if_logged_in { @event = Event.find_by_id params[:id] }
  end

  def new
    if_logged_in { @event = Event.new }
  end

  def edit
    if_logged_in { @event = Event.find_by_id params[:id] }
  end

  def update
    this_event = Event.find_by_id params[:id]
    event = params[:event]
    levels = this_event.sponsorships.group("level").count.keys
    date =  DateTime.new(event["date(1i)"].to_i,
                      event["date(2i)"].to_i,
                      event["date(3i)"].to_i,
                      event["date(4i)"].to_i,
                      event["date(5i)"].to_i,
                      0,
                      ((Time.zone.utc_offset / 60) / 60).to_s)
    speakers = lambda{
      s = event[:speaker_ids]
      s.map! { |x| x = Speaker.find_by_id(x.to_i) }
      s
    }.call
    sponsors = lambda{
      s = params[:sponsors].inject([]) { |arr,(k,v)| arr << v[:sponsor_ids] }.flatten
      s.map! { |x| x = Sponsor.find_by_id x }
    }.call
    agenda = Hash[params[:agenda].sort].inject([]) { |c, (k,v)|
      v[:speaker] = Speaker.find_by_id v[:speaker].to_i
      c << v
    }
    venue = Venue.find_by_id event[:venue]
    Event.update params[:id], { name: event[:name],
                                date: date,
                                site_url: (event[:site_url] == "" ? nil : event[:site_url]),
                                reg_url: (event[:reg_url] == "" ? nil : event[:reg_url]),
                                venue: venue,
                                agenda: agenda,
                                speakers: speakers,
                                sponsors: sponsors,
                                venue: venue,
                                live: event[:live] }
    Hash[params[:sponsors].sort].each do |k,v|
      v[:sponsor_ids].each do |id|
        sponsorship_id = Sponsorship.where(event_id: this_event.id, sponsor_id: id).first.id
        Sponsorship.update sponsorship_id, level: v[:level]
      end
    end
    flash[:message] = this_event.to_s + " updated successfully!"
    redirect_to event_path(this_event)
    return
  end

  def create
    event = params[:event]
    date =  DateTime.new(event["date(1i)"].to_i,
                         event["date(2i)"].to_i,
                         event["date(3i)"].to_i,
                         event["date(4i)"].to_i,
                         event["date(5i)"].to_i,
                         0,
                         ((Time.zone.utc_offset / 60) / 60).to_s)
    speakers = lambda{
      s = event[:speaker_ids]
      s.map! { |x| x = Speaker.find_by_id(x.to_i) }
      s
    }.call
    sponsors = lambda{
      s = params[:sponsors].inject([]) { |arr,(k,v)| arr << v[:sponsor_ids] }.flatten
      s.map! { |x| x = Sponsor.find_by_id x }
    }.call
    venue = Venue.find_by_id event[:venue]
    this_event = Event.new name: event[:name],
                           date: date,
                           site_url: (event[:site_url] == "" ? nil : event[:site_url]),
                           reg_url: (event[:reg_url] == "" ? nil : event[:reg_url]),
                           venue: venue,
                           speakers: speakers,
                           sponsors: sponsors,
                           venue: venue,
                           live: event[:live]
    if this_event.save
      Hash[params[:sponsors].sort].each do |k,v|
        v[:sponsor_ids].each do |id|
          sponsorship_id = Sponsorship.where(event_id: this_event.id, sponsor_id: id).first.id
          Sponsorship.update sponsorship_id, level: v[:level]
        end
      end
      flash[:message] = this_event.to_s + " created successfully!"
      redirect_to event_path(this_event)
      return
    else
      flash[:message] = "Something went wrong. Please try again."
      redirect_to new_event_path
      return
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_agenda_form.haml
.agenda-form
  = label_tag 'time:'
  = text_field_tag "agenda[#{counter}[time]]", (item[:time] if item)
  = label_tag 'title:'
  = text_field_tag "agenda[#{counter}[title]]", (item[:title] if item)
  = label_tag 'speaker:'
  = select_tag "agenda[#{counter}[speaker]]", options_from_collection_for_select(event.speakers, "id", "name", (item[:speaker].id if item && item[:speaker])), include_blank: true
  %a.del-agenda-item{ href: '#' } Delete this timeslot

app/views/events/_sponsor_form.haml
.sponsor-form
  %b Sponsorship Level:
  = text_field_tag "sponsors[#{counter}][level]", (level if level)
  %a.del-sponsor-item{ href: '#' } Delete this level
  / = sponsors.ids
  / = sponsors.inspect
  .sponsors-select
    - num = Sponsor.count
    - slice_num = (num / 3) + (num % 3)
    - Sponsor.order(:name).each_slice(slice_num) do |slice|
      .sponsor-column
        - slice.each do |s|
          = check_box_tag "sponsors[#{counter}][sponsor_ids][]", s.id, (sponsors.include?(s) if sponsors)
          = s
          %br

app/views/events/edit.html.haml
- agenda_counter = 0
- sponsor_counter = 0
%h1= "Edit " + @event.name
%br
%br
= form_for @event, html: { class: "edit-event-form" } do |f|
  %b Name:
  = f.text_field :name, required: true
  %br
  %b Date & Time:
  = f.datetime_select :date
  %br
  %b Location:
  = f.collection_select :venue, Venue.order(:name),:id,:name, selected: @event.venue.id
  Need to add a new venue? Do so <a href="#{new_venue_path}" target="_blank">here</a> first.
  %br
  %b Speakers:
  %br
  .speakers-select
    - num = Speaker.count
    - slice_num = (num / 3) + (num % 3)
    - Speaker.order(:last_name).each_slice(slice_num) do |slice|
      .speaker-column
        - slice.each do |s|
          = check_box_tag "event[speaker_ids][]", s.id, @event.speakers.include?(s)
          = s
          %br
  %div{ style: "clear:both;" }
  %br
  .add-sponsor
    %b Sponsors:
    %br
    %a.add-sponsor-item{ href: '#' } Add sponsorship level
    %br
    - if @event.sponsors.first
      - sponsorships = @event.sponsorships
      - sponsorships.group("level").count.keys.each do |level|
        - sponsors_at_level = @event.sponsorships.where(level: level).inject([]) { |arr,s| arr << s.sponsor }
        = render partial: "sponsor_form", locals: { event: @event, sponsors: sponsors_at_level, level: level, counter: sponsor_counter }
        - sponsor_counter += 1
        %div{ style: "clear:both;" }
    - else
      = render partial: 'sponsor_form', locals: { event: @event, counter: sponsor_counter, level: nil, sponsors: nil }
      - sponsor_counter += 1
      %div{ style: "clear:both;" }
  %div{ style: "clear:both;" }
  %br
  %b Should this event go live?
  = f.check_box :live
  %br
  %b URL for event website:
  = f.text_field :site_url
  %br
  %b URL for Regsistration website:
  = f.text_field :reg_url
  %br
  .add-agenda
    %b Agenda:
    %br
    %a.add-agenda-item{ href: '#' } Add timeslot
    %br
    - if @event.agenda
      - @event.agenda.each do |item|
        = render partial: "agenda_form", locals: { event: @event, item: item, counter: agenda_counter }
        - agenda_counter += 1
    - else
      = render partial: "agenda_form", locals: { event: @event, item: nil, counter: agenda_counter }
      - agenda_counter += 1
  = f.submit
.new-agenda-item{ style: "display:none;" }
  = render partial: "agenda_form", locals: { event: @event, item: nil, counter: agenda_counter }
.new-sponsor-item{ style: "display:none;" }
  = render partial: "sponsor_form", locals: { event: @event, counter: sponsor_counter, level: nil, sponsors: nil }
  %div{ style: "clear:both;" }
.agenda-counter{ style: "display:none;" }
  = agenda_counter
.sponsor-counter{ style: "display:none;" }
  = sponsor_counter

app/views/events/index.html.haml
%h1 List of Events
%br
%br
- @events_by_year.each do |year, events_arr|
  %h2= year
  %br
  %ul
    - events_arr.each do |event|
      %li
        - if !event.live
          %span.not-live (Not Live)
        - else
          %span.live (Live)
        %a{ href: "#{event_path event}" } #{event.name} (#{event.date.strftime "%b. %e"})

  %br

app/views/events/new.html.haml
- sponsor_counter = 0
%h1 New Event
%br
%br
= form_for @event, html: { class: "new-event-form" } do |f|
  %b Name:
  = f.text_field :name, required: true
  %br
  %b Date & Time:
  = f.datetime_select :date
  %br
  %b Location:
  = f.collection_select :venue, Venue.order(:name),:id,:name
  Need to add a new venue? Do so <a href="#{new_venue_path}" target="_blank">here</a> first.
  %br
  %b Speakers:
  %br
  .speakers-select
    - num = Speaker.count
    - slice_num = (num / 3) + (num % 3)
    - Speaker.order(:last_name).each_slice(slice_num) do |slice|
      .speaker-column
        - slice.each do |s|
          = check_box_tag "event[speaker_ids][]", s.id
          = s
          %br
  %div{ style: "clear:both;" }
  %br
  .add-sponsor
    %b Sponsors:
    %br
    %a.add-sponsor-item{ href: '#' } Add sponsorship level
    %br
    = render partial: 'sponsor_form', locals: { event: @event, counter: sponsor_counter, level: nil, sponsors: nil }
    - sponsor_counter += 1
    %div{ style: "clear:both;" }
  %div{ style: "clear:both;" }
  %br
  %b Should this event go live?
  = f.check_box :live
  %br
  %b URL for event website:
  = f.text_field :site_url
  %br
  %b URL for Regsistration website:
  = f.text_field :reg_url
  %br
  .add-agenda
    %b Agenda:
    %br
    You can add the agenda once you create the event.
  = f.submit
.new-sponsor-item{ style: "display:none;" }
  = render partial: "sponsor_form", locals: { event: @event, counter: sponsor_counter, level: nil, sponsors: nil }
  %div{ style: "clear:both;" }
.sponsor-counter{ style: "display:none;" }
  = sponsor_counter

app/views/events/show.html.haml
%h1= @event.name + " (#{@event.date.year})"
%br
%br
%b Date & Time:
%br
= @event.date.strftime "%B %e, %Y at %l:%M %p"
%br
%br
%b Location:
%br
%a{ href: "#{venue_path @event.venue}" }= @event.venue
%br
%br
%b Speakers:
%ul
  - @event.speakers.order(:last_name).each do |speaker|
    %li
      %a{ href: "#{speaker_path speaker}" }= speaker
%br
%br
%b Sponsors
%ul
  - @event.sponsorships.group("level").count.keys.each do |level|
    - sponsors = @event.sponsorships.where(level: level).inject([]) { |arr,s| arr << s.sponsor }
    %b= level
    %ul
      - sponsors.each do |s|
        %li
          %a{ href: "#{sponsor_path s}" }= s

%br
%br
%b Agenda:
%br
- if @event.agenda
  - @event.agenda.each do |i|
    = i[:time]
    %br
    = i[:title]
    %br
    - if i[:speaker]
      %a{ href: "#{speaker_path i[:speaker]}" }= i[:speaker]
    %br
    %br
- else
  "No agenda has been set for this event yet."
  %br
  %br
%b Registration URL:
%br
- if @event.reg_url
  %a{ href: "#{@event.reg_url}" }= @event.reg_url
- else
  = "No registration URL has been set yet"
%br
%br
%b Event Site URL:
%br
- if @event.site_url
  %a{ href: "#{@event.site_url}" }= @event.site_url
- else
  = "No site URL has been set yet"
%br
%br
%a{ href: "#{edit_event_path @event}" } Edit #{@event}
%br
%a{ href: "#{events_path}" } Back to all events