config/routes.rb
Rails.application.routes.draw do

  root 'about#index'
  get 'about/speakers' => 'about#speakers'
  get 'about' => 'about#about'
  get 'calendar' => 'about#calendar'
  get 'about/sponsor' => 'about#sponsor'
  get 'about/request-to-speak' => 'about#request_to_speak'

  resources :users, only: [:new, :create]
  get 'users/validate/:id' => 'users#validate', as: 'validate_user'
  get 'users/profile' => 'users#show', as: 'user_profile'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'users/edit' => 'users#edit', as: 'edit_user'
  get 'users/edit/password' => 'users#edit_password', as: 'edit_user_password'
  patch 'users/update' => 'users#update', as: 'user'
  patch 'users/update/password' => 'users#update_password', as: 'update_user_password'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  get 'logout' => 'sessions#logout'

  resources :speakers

  resources :venues

  resources :sponsors

  resources :agencies

  resources :events
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :employees, class_name: "Speaker"

  def to_s
    self.name
  end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

  def index
    if_logged_in { @agencies = Agency.all.order "name" }
  end

  def show
    agency = Agency.find_by_id params[:id]
    if logged_in? && agency
      @agency = agency
    elsif !agency
      flash[:message] = "Sorry, that agency / employer doesn't exist!"
      redirect_to agencies_path
    else
      not_logged_in
    end
  end

  def edit
    if_logged_in { @agency = Agency.find_by_id params[:id] }
  end

  def update
    agency = Agency.find_by_id params[:id]
    Agency.update agency.id, agency_params
    redirect_to agency_url(agency)
  end

  def new
    if_logged_in { @agency = Agency.new }
  end

  def create
    agency = Agency.new agency_params
    if agency.save!
      flash[:message] = agency.name + " successfully created!"
      redirect_to agency_path(agency)
    else
      flash[:message] = "An error occurred, please try again."
      redirect_to new_agency_path
    end
  end

  # def destroy
  #   agency = agency.find_by_id params[:id]
  #   agency_name = agency.name
  #   if agency.destroy!
  #     flash[:message] = agency_name + " successfully deleted!"
  #     redirect_to agencies_path
  #   else
  #     flash[:message] = "An error occurred."
  #     redirect_to agency_path(agency)
  #   end
  # end

  private

  def agency_params
    params.require(:agency).permit(:name)
  end

end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/edit.html.haml
%h1 Edit #{@agency.name}
%br
%br
= form_for @agency do |f|
  Name:
  = f.text_field :name
  %br
  = f.submit "Save", onclick: "return confirm('Are you sure you want to make these changes to #{@agency.name}?')"

app/views/agencies/index.html.haml
%h1 List of Agencies / Employers
%a{ href: "#{new_agency_path}" } Add new agency / employer
%br
%br
%ul.agency-list
  - @agencies.each do |agency|
    %li.agency-item
      %a{ href: "#{agency_path agency}" }= agency.name

app/views/agencies/new.html.haml
%h1 New Agency / Employer
%br
%br
= form_for @agency do |f|
  Name:
  = f.text_field :name
  %br
  = f.submit "Submit"

app/views/agencies/show.html.haml
%h1= @agency.name + " (Agency / Employer)"
%br
%br
%p Employees of #{@agency.name} in our database:
%p
  - if @agency.employees.first
    %ul
      - @agency.employees.each do |employee|
        %li
          %a{ href: "#{speaker_path employee}" }= employee.name
  - else
    #{@agency.name} doesn't have any employees in our database.
%br
%br
%a{ href: "#{edit_agency_path @agency}" } Edit #{@agency.name}
%br
%a{ href: "#{agencies_path}" } Back to all agencies
%br
/= button_to "Delete #{@agency.name}", @agency, method: :delete, onclick: "return confirm('Are you sure you want to delete #{@agency.name}?')"