config/routes.rb
Rails.application.routes.draw do

  root 'about#index'
  get 'about/speakers' => 'about#speakers'
  get 'about' => 'about#about'
  get 'calendar' => 'about#calendar'
  get 'about/sponsor' => 'about#sponsor'
  get 'about/request-to-speak' => 'about#request_to_speak'

  resources :users, only: [:new, :create]
  get 'users/validate/:id' => 'users#validate', as: 'validate_user'
  get 'users/profile' => 'users#show', as: 'user_profile'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'users/edit' => 'users#edit', as: 'edit_user'
  get 'users/edit/password' => 'users#edit_password', as: 'edit_user_password'
  patch 'users/update' => 'users#update', as: 'user'
  patch 'users/update/password' => 'users#update_password', as: 'update_user_password'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  get 'logout' => 'sessions#logout'

  resources :speakers

  resources :venues

  resources :sponsors

  resources :agencies

  resources :events
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_many :speaking_engagements
  has_many :events, through: :speaking_engagements
  belongs_to :employer, class_name: "Agency", foreign_key: "agency_id"

  has_attached_file :photo, :styles => { :huge => "1000x1000#", :large => "700x700#", :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/missing/missing_:style.jpg"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  process_in_background :photo

  def name
    return "#{self.first_name} #{self.last_name}"
  end

  alias :to_s :name

end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController

  def index
    if_logged_in { @speakers = Speaker.all.order("last_name") }
  end

  def show
    speaker = Speaker.find_by_id(params[:id])
    if logged_in? && speaker
      @speaker = speaker
    elsif !speaker
      flash[:message] = "Sorry, that speaker doesn't exist!"
      redirect_to speakers_path
    else
      not_logged_in
    end
  end

  def edit
    if_logged_in { @speaker = Speaker.find_by_id(params[:id]) }
  end

  def update
    speaker = Speaker.find_by_id params[:id]
    s_params = speaker_params
    s_params[:employer] = Agency.find_by_id s_params[:employer]
    if Speaker.update speaker.id, s_params
      Delayed::Worker.new.work_off
      if params[:remove_photo]
        speaker.photo = nil
        speaker.save!
      end
      flash[:message] = speaker.name + " updated successfully!"
      redirect_to speaker_path(speaker)
    else
      flash[:message] = "Oops, something went wrong"
      redirect_to edit_speaker_path(speaker)
    end
  end

  def new
    if_logged_in { @speaker = Speaker.new }
  end

  def create
    s_params = speaker_params
    s_params[:employer] = Agency.find_by_id s_params[:employer]
    @speaker = Speaker.new(s_params)
    if @speaker.save
      Delayed::Worker.new.work_off
      flash[:message] = "Created #{@speaker.name} successfully!"
      redirect_to speaker_path(@speaker)
    else
      flash[:message] = "Oops, something went wrong"
      redirect_to new_speaker_path
    end
  end

  def destroy
    @speaker = Speaker.find_by_id params[:id]
    speaker_name = @speaker.name
    if @speaker.destroy!
      flash[:message] = "#{speaker_name} successfully deleted"
      redirect_to speakers_path
    else
      flash[:message] = "An error occurred."
      redirect_to speaker_path(@speaker)
    end
  end

  private

  def speaker_params
    params.require(:speaker).permit(:first_name, :last_name, :job_title, :employer, :bio, :photo, :govie)
  end

end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/edit.html.haml
%h1 Edit #{@speaker.name}
%br
.form
  %img{ src: "#{@speaker.photo.url :medium}", width: '200', height: '200' }
  %br
  = form_for @speaker, html: { id: 'edit-speaker-form' } do |f|
    %b First Name:
    = f.text_field :first_name
    %br
    %b Last Name:
    = f.text_field :last_name
    %br
    %b Job Title:&nbsp&nbsp&nbsp&nbsp
    = f.text_field :job_title, style: "width: 300px;"
    %br
    %b Employer:
    = f.collection_select :employer, Agency.order(:name),:id,:name, selected: @speaker.employer.id
    %br
    %b Bio:
    %br
    = f.text_area :bio, {rows: "5", cols: "50"}
    %br
    %b Image:
    %span{ style: 'color:red;' } PLEASE MAKE SURE IMAGE IS SQUARE.
    %br
    If it isn't already square, it will be cropped to make it square automatically and may not look good.
    %br
    Also make sure it is as high resolution as possible.
    %br
    = f.file_field :photo
    %br
    %b Remove photo?
    = check_box_tag :remove_photo
    %br
    %b Work for the Government?
    = f.check_box :govie
    %br
    = f.submit "Save", onclick: "return confirm('Are you sure you want to make these changes to #{@speaker.name}?')"

.wait-overlay
  %img{ src: '/images/loading.gif' }

app/views/speakers/index.html.haml
%h1 List of Speakers
%a{ href: "#{new_speaker_path}" } Add new speaker
%hr
.speaker-list
  - @speakers.each do |speaker|
    .speaker-card
      %a{ href: "#{speaker_path speaker}" }
        %img{ src: "#{speaker.photo.url :medium}", width: "200", height: '200' }
      %br
      %p
        %a.speaker-name{ href: "#{speaker_path speaker}" }
          = speaker.last_name + ", " + speaker.first_name
      %p.speaker-title= speaker.job_title
      %p.speaker-employer= speaker.employer

app/views/speakers/new.html.haml
%h1 New Speaker
%br
.form
  = form_for @speaker, html: { id: 'new-speaker-form' } do |f|
    %b First Name:
    = f.text_field :first_name, required: true
    %br
    %b Last Name:
    = f.text_field :last_name, required: true
    %br
    %b Job Title:&nbsp&nbsp&nbsp&nbsp
    = f.text_field :job_title, required: true, style: "width: 300px;"
    %br
    %b Employer:
    = f.collection_select :employer, Agency.order(:name),:id,:name
    / %br
    Need to add a new Employer?
    %a{ href: "#{new_agency_path}", target: "_blank" } Click here
    %br
    %b Bio:
    %br
    = f.text_area :bio, {rows: "5", cols: "50", required: true}
    %br
    %b Image:
    %span{ style: 'color:red;' } PLEASE MAKE SURE IMAGE IS SQUARE.
    %br
    If it isn't already square, it will be cropped to make it square automatically and may not look good.
    %br
    Also make sure it is as high resolution as possible.
    %br
    = f.file_field :photo
    %br
    %b Work for the Government?
    = f.check_box :govie
    %br
    = f.submit "Submit"

.wait-overlay
  %img{ src: '/images/loading.gif' }

app/views/speakers/show.html.haml
%h1= @speaker.name + " (Speaker)"
%hr
%img{ src: "#{@speaker.photo.url(:medium)}", height: '200', width: '200' }
%br
%br
%b Job Title: #{@speaker.job_title}
%p
  Employer:
  %a{ href: "#{agency_path @speaker.employer}" }= @speaker.employer
%p
  %b Bio:
  %br
  = @speaker.bio
%br
%b Events #{@speaker.name} has spoken / will speak at:
%p
  - if @speaker.events.first
    %ul
      - @speaker.events.each do |event|
        %li
          %a{ href: "#" }= event.name
  - else
    #{@speaker.name} hasn't spoken at any events
- if @speaker.govie
  %span{ style: 'color:blue;' } #{@speaker.name} is a government employee
%br
%br
%a{ href: "#{edit_speaker_path @speaker}" } Edit #{@speaker.name}
%br
%a{ href: "#{speakers_path}" } Back to all speakers
%br
= button_to "Delete #{@speaker.first_name}", @speaker, method: :delete, onclick: "return confirm('Are you sure you want to delete #{@speaker.name}?')"